# Generated by Django 2.2.4 on 2020-12-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
    ]
